import { readFileSync, writeFileSync } from 'node:fs';
const assets = Object.fromEntries(['status.html', 'status.js', 'status.css', 'styles.css', 'logo.css', 'footer.css'].map(name => [`/${name}`, readFileSync(`web/${name}`, 'utf8').replace(/\r\n/g, '\n')]));
assets['/'] = assets['/status.html'];
writeFileSync('deploy/status-assets.js', `// Generated by node tools/generate_status_assets.mjs\nexport const STATUS_ASSETS = ${JSON.stringify(assets, null, 2)};\n`);
